name: 'primes-type'
version: '0.1.0.0'
license: UnspecifiedLicense
library:
    source-dirs: src
    exposed-modules: Data.Numbers.Primes.Type
    dependencies:
    - base >=4.5 && <5
    - primes
    - timeout
tests:
  primes-type-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - primes
    - primes-type
    - HTF
