name: 'primes-type'
version: '0.1.0.0'
category: Algorithms, Numerical
author: Ignat Insarov
maintainer: kindaro@gmail.com
copyright: 2017 Ignat Insarov
license: ISC
github: kindaro/primes-type
synopsis: Type-safe prime numbers.
description: This library provides type safe prime numbers. The idea is based upon the concept of a predicate type from type theory.
library:
    source-dirs: src
    exposed-modules: Data.Numbers.Primes.Type
    dependencies:
    - base >=4.5 && <5
    - primes
tests:
  primes-type-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.5 && <5
    - primes
    - primes-type
    - HTF
